language: node_js
sudo: required
node_js: 
  - 7.9.0

cache:
  directories:
    - node_modules

branches:
  only:
    - source 

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "FreedomLy"
  - git config user.email "Freedom.JFL@gmail.com"
  - git clone https://github.com/Felon03/Felon03.github.io.git .deploy_git # 解决 commit 清空问题
  - cd .deploy_git
  - git checkout master
  - cd ../
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle