language: node_js
sudo: required
node_js: 
  - 10.19.0

cache:
  directories:
    - node_modules

branches:
  only:
    - source 

git:
  depth: false
  # submodules: false

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - npm install -g hexo-cli
  # Restore last modified time
  - "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
  # - git config user.name "FreedomLy"
  # - git config user.email "Freedom.JFL@gmail.com"
  # - chmod +x git_reset_mtime.py
  # - python3 ./git_reset_mtime.py


# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save
  - npm install --save hexo-algolia

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - export HEXO_ALGOLIA_INDEXING_KEY='5e82fb4a75535312cb85cdb8b298443e'
  - hexo algolia
  - hexo generate

after_script:
  - git config user.name "FreedomLy"
  - git config user.email "Freedom.JFL@gmail.com"
  - git clone https://github.com/feilongjiang/feilongjiang.github.io.git .deploy_git # 解决 commit 清空问题
  - cd .deploy_git
  - git checkout master
  - cd ../
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle